site_name: AP US History
pages:
    - Home: index.md
    - About: about.md
    - Environment and Geography: environment.md
    - Continuity and Change: ccot.md
    - Complexity: complexity.md
theme: material
